### ISSUE TITLE
Allocating bits to a smaller range

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#16]
Not sure if this is feasible, but I remember you mentioned that we can allocate a portion of the bits over a certain capacitance range to improve the signal resolution. This would be something interesting to explore. 

* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by taoyilee** [comment]
This feature requires modifications on the hardware. Tentatively closed.
