### ISSUE TITLE
Add world/network timestamp in the output file

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#18]
Include the network/world time stamp for very first measurement.

* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by taoyilee** [comment]
Feature added to version [0.6.0](https://github.com/taoyilee/bp_demo/releases/tag/0.6.0)
