### ISSUE TITLE
Autoscaling y-axes

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#3]
* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by JoshKim599** [comment]
1. Autoscaling y-axes
2. Ability to switch from measuring from one or two channels
3. Ability to modify the x-axes length (window size)

**Comment by JoshKim599** [comment]
4. Log Data Function

If you are able to write a LabView code for this, all of this could be easily fixed.

**Comment by taoyilee** [comment]
@JoshKim599  Do you mind separating each item to an independent issue :)

**Comment by taoyilee** [comment]
Closed due to redundancy
