### ISSUE TITLE
Ability to switch from measuring from one or two channels

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#4]
* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by taoyilee** [comment]
Addressed in commit 5f14453c82a1be0481b44f7939df4e22f6e7730d
