### ISSUE TITLE
Baseline correction (control where baseline is to keep measurements within range) 

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#6]
* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by taoyilee** [comment]
Just to make sure we are on the same page, by baseline, we are talking about AD7746 DAC values. 
Controls will be added to allow real time adjustment of DAC values.

**Comment by JoshKim599** [comment]
Yes, the ability to change the DAC values in real time would be perfect. This is to ensure that the measurements are within range of the ADC to measure.

**Comment by taoyilee** [comment]
Feature added to version [0.6.0](https://github.com/taoyilee/bp_demo/releases/tag/0.6.0)
