### ISSUE TITLE
LabView Compatibility

### ISSUE THREAD

**Issue by JoshKim599** [taoyilee/bp_demo#7]
* UCI cBP demo version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by taoyilee** [comment]
Close for now. We can reopen if there is a strong reason why we should migrate to LV.
